### ISSUE TITLE
Update image version

### ISSUE THREAD

**Issue by josem-gp** [nfedyashev/retryable#39]
Hi, 

The version 3.0.5 is from [2019](https://rubygems.org/gems/retryable/versions/3.0.5).
There are changes being made since then. I am interested specifically the ruby compatibility for the v3.1 and v3.2 that was done in Jan 2023.
Are those changes inside of 3.0.5 version? Do you plan on releasing a new image version?

Thanks!

**Comment by nfedyashev** [comment]
See https://github.com/nfedyashev/retryable/issues/38

Yes, 3.0.5 is compatible with 3.1 and 3.2 Ruby versions
